import { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Welcome to Homepage',
    description: 'Generated by create next app',
}

const Homepage = () => {
    console.log('What type of component am i')
    return <div className="text-5xl underline">Home Page</div>
}

export default Homepage
